
trigger:
  branches:
    include:
      - master
      - feature/*
      - issue/*
  paths:
    exclude:
      - README.md

variables:
  major: 1
  minor: 0
  patch: 0
  rev: rev-$(git rev-parse --short HEAD)
  version: "v$(go run version.go)"

stages:
  - stage: Build_Test_Lint_Tag
    displayName: 'Build, Test, Lint, Tag'
    jobs:
      - job: Sender_Build_Test_Lint
        displayName: '[Sender] Build, Test, Lint'
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - template: ci/steps/steps-build.yml
            parameters:
              workingDir: 'sender'

      - job: Reveiver_Build_Test_Lint
        dependsOn: Sender_Build_Test_Lint
        displayName: '[Receiver] Build, Test, Lint'
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - template: ci/steps/steps-build.yml
            parameters:
              workingDir: 'receiver'

      - job: GitTag
        dependsOn: Reveiver_Build_Test_Lint
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        displayName: 'Release and Tag'
        pool:
          vmImage: 'ubuntu-18.04'
        steps:
          - script: make release
            displayName: "Github Release"
